// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCULW5_wVVD_ISYkSIZ5qypsyU_t688rBE',
    appId: '1:455824777024:web:11ef168a961f7a916b64a5',
    messagingSenderId: '455824777024',
    projectId: 'hybrid-check-list',
    authDomain: 'hybrid-check-list.firebaseapp.com',
    storageBucket: 'hybrid-check-list.appspot.com',
    measurementId: 'G-KXM3J695C3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Dmr9DrMg82W9JYV9IB056Anmbm3CIcM',
    appId: '1:455824777024:android:801789b1319a035c6b64a5',
    messagingSenderId: '455824777024',
    projectId: 'hybrid-check-list',
    storageBucket: 'hybrid-check-list.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD68g1CWesj19DKcdEGC4TaQvXof-65Ve4',
    appId: '1:455824777024:ios:25bd8a8b9dfa5eb76b64a5',
    messagingSenderId: '455824777024',
    projectId: 'hybrid-check-list',
    storageBucket: 'hybrid-check-list.appspot.com',
    iosBundleId: 'com.example.hybridCheckList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD68g1CWesj19DKcdEGC4TaQvXof-65Ve4',
    appId: '1:455824777024:ios:9467f8e213bd82d86b64a5',
    messagingSenderId: '455824777024',
    projectId: 'hybrid-check-list',
    storageBucket: 'hybrid-check-list.appspot.com',
    iosBundleId: 'com.example.hybridCheckList.RunnerTests',
  );
}
